export const permissionsSeed = [
  ['account.read', 'Read accounts', 'View account directory', 'Accounts'],
  ['account.create', 'Create accounts', 'Create account invitations', 'Accounts'],
  ['account.update', 'Update accounts', 'Edit account metadata', 'Accounts'],
  ['account.suspend', 'Suspend account', 'Suspend active accounts', 'Accounts'],
  ['account.restore', 'Restore account', 'Restore suspended accounts', 'Accounts'],
  ['account.role.assign', 'Assign role', 'Change assigned role', 'Accounts'],
  ['account.session.revoke', 'Revoke session', 'Revoke active sessions', 'Sessions'],
  ['role.read', 'Read roles', 'View roles', 'Roles'],
  ['role.manage', 'Manage roles', 'Edit roles and mappings', 'Roles'],
  ['permission.read', 'Read permissions', 'View permission matrix', 'Roles'],
  ['audit.read', 'Read audit log', 'View audit events', 'Security'],
  ['audit.export', 'Export audit log', 'Export audit events', 'Security'],
  ['flight.read.all', 'Read all flights', 'View network flights', 'Operations'],
  ['flight.read.assigned', 'Read assigned flights', 'View own flights', 'Operations'],
  ['flight.manage', 'Manage flights', 'Update flight operations', 'Operations'],
  ['schedule.read.own', 'Read own schedule', 'View own schedule', 'Scheduling'],
  ['schedule.read.team', 'Read team schedule', 'View team schedule', 'Scheduling'],
  ['schedule.manage', 'Manage schedule', 'Build and publish roster', 'Scheduling'],
  ['crew.assign', 'Assign crew', 'Assign crew to flights', 'Scheduling'],
  ['leave.request', 'Request leave', 'Submit leave request', 'Approvals'],
  ['leave.read.own', 'Read own leave', 'View own leave requests', 'Approvals'],
  ['leave.approve', 'Approve leave', 'Approve or reject leave', 'Approvals'],
  ['swap.request', 'Request swap', 'Submit shift swap', 'Approvals'],
  ['swap.approve', 'Approve swap', 'Approve or reject swaps', 'Approvals'],
  ['maintenance.read', 'Read maintenance', 'View maintenance records', 'Maintenance'],
  ['maintenance.manage', 'Manage maintenance', 'Manage work orders', 'Maintenance'],
  ['aircraft.clear', 'Clear aircraft', 'Clear aircraft for release', 'Maintenance'],
  ['aircraft.ground', 'Ground aircraft', 'Ground aircraft', 'Maintenance'],
]

export const rolePermissionMap = {
  SYSTEM_ADMIN: permissionsSeed.map(([code]) => code),
  OPERATIONS_MANAGER: [
    'flight.read.all',
    'flight.manage',
    'schedule.read.team',
    'maintenance.read',
    'audit.read',
  ],
  CREW_SCHEDULER: [
    'flight.read.all',
    'schedule.read.team',
    'schedule.manage',
    'crew.assign',
    'leave.read.own',
    'maintenance.read',
  ],
  SUPERVISOR: [
    'schedule.read.team',
    'leave.approve',
    'swap.approve',
    'leave.read.own',
    'flight.read.all',
  ],
  FLIGHT_CREW: [
    'flight.read.assigned',
    'schedule.read.own',
    'leave.request',
    'leave.read.own',
    'swap.request',
  ],
  MAINTENANCE_TECHNICIAN: [
    'maintenance.read',
    'maintenance.manage',
    'aircraft.clear',
    'aircraft.ground',
    'flight.read.all',
  ],
}
