import {
  Activity,
  AlertTriangle,
  CalendarDays,
  ClipboardCheck,
  FileText,
  Gauge,
  KeyRound,
  LayoutDashboard,
  ListChecks,
  Plane,
  ShieldCheck,
  Users,
  Wrench,
} from 'lucide-react'

export const appName = 'ETL Airlines Operation Portal'

export const roleConfig = {
  admin: {
    label: 'System Administrator',
    tone: 'security',
    landing: '/admin/dashboard',
    nav: [
      ['Dashboard', '/admin/dashboard', LayoutDashboard],
      ['Users', '/admin/users', Users],
      ['Roles', '/admin/roles', ShieldCheck],
      ['Permission Matrix', '/admin/permissions', KeyRound],
      ['Invitations', '/admin/invitations', FileText],
      ['Sessions', '/admin/sessions', Activity],
      ['Audit Logs', '/admin/audit', ListChecks],
      ['Security Settings', '/admin/security', ShieldCheck],
    ],
  },
  operations: {
    label: 'Operations Manager',
    tone: 'command',
    landing: '/operations/command-center',
    nav: [
      ['Command Center', '/operations/command-center', LayoutDashboard],
      ['Flights', '/operations/flights', Plane],
      ['Crew Coverage', '/operations/crew-coverage', Users],
      ['Aircraft Status', '/operations/aircraft', Wrench],
      ['Disruptions', '/operations/disruptions', AlertTriangle],
      ['Performance', '/operations/performance', Gauge],
      ['Reports', '/operations/reports', FileText],
    ],
  },
  scheduler: {
    label: 'Crew Scheduler',
    tone: 'scheduler',
    landing: '/scheduler/roster',
    nav: [
      ['Schedule Board', '/scheduler/roster', CalendarDays],
      ['Weekly Roster', '/scheduler/weekly', CalendarDays],
      ['Monthly Calendar', '/scheduler/monthly', CalendarDays],
      ['Flight Assignments', '/scheduler/assignments', Plane],
      ['Crew Availability', '/scheduler/availability', Users],
      ['Conflict Center', '/scheduler/conflicts', AlertTriangle],
      ['Reserve Crew', '/scheduler/reserve', ClipboardCheck],
      ['Assignment History', '/scheduler/history', FileText],
    ],
  },
  supervisor: {
    label: 'Supervisor',
    tone: 'supervisor',
    landing: '/supervisor/approvals',
    nav: [
      ['Approval Queue', '/supervisor/approvals', ClipboardCheck],
      ['Leave Requests', '/supervisor/leave', CalendarDays],
      ['Swap Requests', '/supervisor/swaps', Users],
      ['Replacement Requests', '/supervisor/replacements', Plane],
      ['Team Overview', '/supervisor/team', Users],
      ['Escalations', '/supervisor/escalations', AlertTriangle],
      ['Approval History', '/supervisor/history', FileText],
    ],
  },
  crew: {
    label: 'Flight Crew Member',
    tone: 'crew',
    landing: '/crew/dashboard',
    nav: [
      ['My Dashboard', '/crew/dashboard', LayoutDashboard],
      ['My Schedule', '/crew/schedule', CalendarDays],
      ['Flight Details', '/crew/flights', Plane],
      ['My Requests', '/crew/requests', ClipboardCheck],
      ['Qualifications', '/crew/qualifications', ShieldCheck],
      ['Documents', '/crew/documents', FileText],
      ['Notifications', '/crew/notifications', Activity],
      ['Account & Security', '/crew/security', KeyRound],
    ],
  },
  maintenance: {
    label: 'Maintenance Technician',
    tone: 'maintenance',
    landing: '/maintenance/dashboard',
    nav: [
      ['Dashboard', '/maintenance/dashboard', LayoutDashboard],
      ['Work Orders', '/maintenance/work-orders', Wrench],
      ['Aircraft', '/maintenance/aircraft', Plane],
      ['Inspections', '/maintenance/inspections', ListChecks],
      ['Defects', '/maintenance/defects', AlertTriangle],
      ['Clearance', '/maintenance/clearance', ShieldCheck],
      ['Parts Requests', '/maintenance/parts', ClipboardCheck],
      ['History', '/maintenance/history', FileText],
      ['Handover Notes', '/maintenance/handover', FileText],
    ],
  },
}
